name: Notifications

on:
  workflow_run:
    workflows: ["CI/CD Pipeline", "Release Management"]
    types: [completed]

jobs:
  notify:
    name: Send Notifications
    runs-on: ubuntu-latest
    if: github.event.workflow_run.conclusion != 'success'

    steps:
    - name: Send Slack notification on failure
      if: env.SLACK_WEBHOOK_URL != ''
      uses: 8398a7/action-slack@v3
      with:
        status: failure
        webhook_url: ${{ secrets.SLACK_WEBHOOK_URL }}
        fields: repo,message,commit,author,action,eventName,ref,workflow
      env:
        SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}

    - name: Send Discord notification on failure
      if: env.DISCORD_WEBHOOK_URL != ''
      uses: tsickert/discord-webhook@v5.3.0
      with:
        webhook-url: ${{ secrets.DISCORD_WEBHOOK_URL }}
        embed-title: "Build Failed"
        embed-description: |
          Workflow: ${{ github.event.workflow_run.name }}
          Status: ${{ github.event.workflow_run.conclusion }}
          Repository: ${{ github.repository }}
          Run: ${{ github.event.workflow_run.html_url }}

    - name: Comment on PR on failure
      if: github.event.workflow_run.event == 'pull_request' && github.event.workflow_run.pull_requests[0].number != ''
      uses: actions/github-script@v7
      with:
        script: |
          const prNumber = ${{ github.event.workflow_run.pull_requests[0].number }};

          await github.rest.issues.createComment({
            issue_number: prNumber,
            owner: context.repo.owner,
            repo: context.repo.repo,
            body: `❌ **Build Failed**

            Workflow: ${{ github.event.workflow_run.name }}
            Status: ${{ github.event.workflow_run.conclusion }}

            [View Details](${{ github.event.workflow_run.html_url }})

            Please check the logs and fix any issues.`
          });
